# Generated by Django 2.2.16 on 2023-03-05 21:35

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0002_auto_20230302_2146'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='name',
            field=models.CharField(db_index=True, max_length=200, validators=[django.core.validators.RegexValidator(message='Is not allowed symbols ^$%^&#:;!', regex='^[^$%^&#:;!]+$')], verbose_name='Наименование'),
        ),
    ]
