# Generated by Django 2.2.16 on 2023-02-05 18:15

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_user_is_subscribed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='password',
            field=models.CharField(max_length=150, validators=[django.core.validators.MinLengthValidator(5)], verbose_name='Пароль'),
        ),
    ]
